FROM ubuntu:18.04

LABEL Developer="Sehun Kim <h95fit@gmail.com>"

# install nginx
RUN apt-get update \
    && apt-get install -y nginx

RUN echo "WebServer Test" > /var/www/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]